# Generated by Django 5.0 on 2023-12-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='address',
            new_name='city',
        ),
    ]
