# Generated by Django 5.0 on 2023-12-23 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_rename_address_jobpost_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.jobpost'),
        ),
    ]
